### ISSUE TITLE
Gun licenses

### ISSUE THREAD

**Issue by Kasup2** [broke-protocol/issues#275] opened 2017-12-04 18:28 UTC
like the licenses kinda. But I think specially the gun license shouldn't be a requirement to enter the gun store. Also its kinda dumb how you might spawn oppisite side of the map from the townhall and have to walk all the way since you can't use cars without a license. Maybe so the gun license is for buying guns not for entering the gun shop. We could have it so that you can't shoot or use guns or something idk or maybe a limit that would automaticly throw ppl out of the gun store after some time or a "Swat" timer and after the timer is up several armed cops come to the gunstore. I just don't like the current way it works specially because some mayors only give them to cops but I don't wanna be a corrupted cop .

**Comment by UserR00T** [comment] 2017-12-04 18:30
`But I think specially the gun license shouldn't be a requirement to enter the gun store` - Copy of #268.

**Comment by TENTACLEBOSS** [comment] 2017-12-04 19:23
If you can enter the gun shop without a license then everyone will just steal guns, and accost the clerc with handcuffs anyway.

Now everything will be exactly the same as it was prior to licenses and none of the gun problems will be resolved.

**Comment by DeathByKorea** [comment] 2017-12-04 19:31
Marking this as a Duplicate of #268 . Not closing because there's some good ideas here.

**Comment by DeathByKorea** [comment] 2017-12-04 19:32
Duplicate of #268

**Comment by Kasup2** [comment] 2017-12-04 20:21
but still I don't like the fact that I need to be a certain job to be allowed to buy guns. (Of course this is not always the case) But specially me playing in the test version that was always the case.

**Comment by Kasup2** [comment] 2017-12-04 20:23
I think there can be an alternative a criminal way but a rly hard one where maybe the "swat team" idea i talked about earlier could be very good in.

**Comment by TENTACLEBOSS** [comment] 2017-12-04 23:43
@Kasup2 Right now I believe the pawn shop can be accessed without a license, as can the loot left over by NPC's. For a low cost of one set of handcuffs you can always pull an NPC over and get a gun. You could also bribe a player with a license to get you a gun in the spirit of RP, or bribe the mayor for a license, kind of like a black market. 

On the cop note, if cops are going to mean anything they need to be able to aim. As it stands nobody cares about the threat of cops/swat because they shoot like neanderthals. So that would need to be changed if SWAT is to ever mean anything.

**Comment by BrokeProtocol** [comment] 2017-12-06 13:29
Instead of restricting access to the gunstore completely, the gun license could be used to purchase restricted weapons like: rocket launcher, full autos, sniper, grenades, but weapons like pistol/shotgun/springfield(or weaker weapons) can be bought without. Plus remove the rocket launcher from display, all I see this being used for is to just blow up everyone in the gun store.

**Closed** 2020-02-14 04:28 UTC
Labels: Suggestion
